app:
  jwt:
    secret-key: ${JWT_SECRET:DPCjgTPZXCu8xz3QgeO07jHn37Koei86ZpUIhW2eAVc=}
    expiration-time: 900000 # 15 minutes
    pre-auth-expiration-time: 300000 # 5 minutes
  mfa:
    issuer: MFA App
    number-of-digits: 6
    period: 30
    scratch-codes-count: 5
  name: mfa-app
  security:
    max-login-attempts: 3
    lockout-duration-minutes: 15

server:
  port: 9099

spring:
  application:
    name: Mfa Application
  datasource:
    url: jdbc:postgresql://localhost:5435/mfa_app_db
    username: tountoun
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  file:
    name: mfa
    path: ${user.home}/${app.name}/logs

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  info:
    title: MFA Application
    version: 1.0.0
    description: Spring Boot MFA compatible Google Authenticator / Authy